---
- name: Ensure Apache is installed on RHEL.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ apache_enablerepo }}"
  with_items: "{{ apache_packages }}"

- name: Remove default ssl.conf
  file: name=/etc/httpd/conf.d/ssl.conf state=absent
  when: apache_listen_port_ssl != 443
